### ISSUE TITLE
Question about pose parameter

### ISSUE THREAD

**Issue by ZCB-endeavor** [PeizhiYan/mediapipe-blendshapes-to-flame#1]
Hi, thank you for your excellent work!
I have a question about the pose parameters. I noticed that the pose shape is np.zeros([1,6],dtype=np.float32), but the FLAME Jaw Pose of README has only 3 parameters. If I want to get a Jaw Pose with 3 parameters, how do I convert the pose parameters so that it changes from 6 to 3.
I'm looking forward to your reply.

**Comment by PeizhiYan** [comment]
Hi!

The first three values in pose are actually zeros, these are the pose for head, but I did not use it. The last three values are the jaw pose.

**Comment by ZCB-endeavor** [comment]
Your answer solved my problem perfectly, thanks a lot!

**Comment by PeizhiYan** [comment]
You are welcome!
